hooks:
  pre-commit:
    - husky lint-staged
    - golangci-lint run ./...
    - go build -o ./bin/pricefinder .
  pre-push:
    - husky lint-staged
    - go build -o ./bin/pricefinder .
  commit-msg:
    - husky lint-commit

# list staged files do some pre-process and git add
lint-staged:
  "*.go":
    - gofmt -l -w

# commit msg rule only support conventional commits
lint-commit:
  types: "^(feat|fix|build|chore|ci|docs|perf|refactor|revert|style|test)$"
